version: '3.8'

services:
  onde-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onde-web
    image: onde-web:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production.local
    volumes:
      # Montar base.js como read-only para segurança
      - ./src/base.js:/app/src/base.js:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - onde-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  onde-network:
    driver: bridge

# Para desenvolvimento, use:
# docker-compose up -d

# Para rebuild:
# docker-compose up -d --build

# Para ver logs:
# docker-compose logs -f

# Para parar:
# docker-compose down
